site_name: OpenML Documentation
# repo_url: https://github.com/openml
repo_url: https://github.com/SubhadityaMukherjee/openml_docs/blob/master/docs
binder_url: SubhadityaMukherjee/openml_docs/tree/master/docs
site_url: https://docs.openml.org/
theme:
  name: "material"
  language: "en"
  palette:
    # primary: darkblue
    primary: white
    accent: indigo
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: img/openmllogo.png
  features:
    - navigation.tabs
    - content.action.edit
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # - fontawesome_markdown
  - admonition
  - toc:
      permalink: true
nav:
  - Welcome: index.md
  - ... | concepts/*
  - Integrations:
      - Python Integrations:
          - Scikit-learn:
              - "Introduction": Scikit-learn/index.md
              - Tutorials:
                  - "Loading a dataset": Scikit-learn/datasets_tutorial.ipynb
          - "Pytorch": Pytorch.md
          - "Tensorflow": Tensorflow.md
          - "Keras": Keras.md
      - R Integrations:
          - MLR: R-integration/mlr.md
  - Ecosystem:
      - "Introduction" : ecosystem.md
      - Community:
          - "WEKA": Weka.md
          - "MOA": MOA.md
          - "Julia": Julia.md 
          - "Java": Java.md
          - "REST API": REST-API.md
      - Developer Guide:
          - "Creating a new integration": creating_extensions.md
  - AutoML:
      - "AutoML Benchmark": automl/AutoML-Benchmark.md
      - "Important Parameters": automl/important_params.md
      - Tutorials:
          - "Basic Example - Random Forest": automl/basic_example.md
          - "Specific Task and Fold": automl/specific_task_fold_example.md
  - Benchmarking: benchmark.md
  - Governance: Governance.md
  - Contributing:
      - "How to Contribute": contributing/Contributing.md
      - "Documenting": contributing/OpenML-Docs.md
      - "Visual Guidelines": contributing/Visual-Guidelines.md
      - "Website":
          - "Getting started": contributing/website/Website.md
          - "Flask backend": contributing/website/Flask.md
          - "React frontend": contributing/website/React.md
          - "Dash visualizations": contributing/website/Dash.md
      - "Backend":
          - "Local Installation": contributing/backend/Local-Installation.md
          - "API Development": contributing/backend/API-development.md
          - "Evaluation Engine": contributing/backend/Java-App.md
      - "OpenML Definition": contributing/OpenML_definition.md
      - "Client Development": contributing/Client-API-Standards.md
      - "Datasets": contributing/Datasets.md
      - "Resources": contributing/resources.md
      - "Terms" : contributing/terms.md
  - Showcase: showcase.md
plugins:
    - mknotebooks
    #     binder: true
    #     binder_service_name: "gh"
    #     binder_branch: "main"
    #     binder_ui: "lab"
    - redirects:
        redirect_maps:
            'APIs.md': 'https://www.openml.org/apis'
            'REST-API.md': 'https://www.openml.org/apis'
    - search:
        separator: '[\s\-\.]+'
        lang:
          - en
    - awesome-pages

extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js

