site_name: OpenML Documentation
repo_url: https://github.com/openml/docs/
site_url: https://docs.openml.org/
edit_uri: edit/master/docs/
theme:
  name: "material"
  language: "en"
  palette:
    primary: darkblue
    accent: indigo
  font:
    text: "Roboto"
    code: "Roboto Mono"
  icon:
    logo: material/library
  features:
    - navigation.tabs
    - content.action.edit
  plugins:
    - search:
      separator: '[\s\-\.]+'
      lang:
        - en
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # - fontawesome_markdown
  - admonition
  - toc:
      permalink: true
nav:
  - Get started: index.md
  - Integrations:
      - Python Integrations:
          - Scikit-learn:
              - "Introduction": Scikit-learn/index.md
              # - "Basic Tutorial": Scikit-learn/sklearn-basic-tutorial.md
              - "Basic Tutorial": Scikit-learn/datasets_tutorial.ipynb
              - "Advanced Tutorial": Scikit-learn/sklearn-advanced-tutorial.md
          - "Pytorch": Pytorch.md
          - "Tensorflow": Tensorflow.md
          - "Keras": Keras.md
      - R Integrations:
          - MLR: R-integration/mlr.md
      - Other Integrations:
          - "WEKA": Weka.md
          - "MOA": MOA.md
          - "Julia": Julia.md 
          - "Java": Java.md
          - "REST API": REST-API.md
      - "Creating a new integration": creating_extensions.md
  - AutoML:
      - "AutoML Benchmark": AutoML-Benchmark.md
  - Benchmarking: benchmark.md
  - Governance: Governance.md
  - Contributing:
      - "How to Contribute": contributing/Contributing.md
      - "Documenting": contributing/OpenML-Docs.md
      - "Website":
          - "Getting started": contributing/website/Website.md
          - "Flask backend": contributing/website/Flask.md
          - "React frontend": contributing/website/React.md
          - "Dash visualizations": contributing/website/Dash.md
      - "Backend":
          - "Local Installation": contributing/backend/Local-Installation.md
          - "API Development": contributing/backend/API-development.md
          - "Evaluation Engine": contributing/backend/Java-App.md
      - "OpenML Definition": contributing/OpenML_definition.md
      - "Client Development": contributing/Client-API-Standards.md
      - "Datasets": contributing/Datasets.md
      - "Resources": contributing/resources.md
      - "Terms" : contributing/terms.md
  - Showcase: showcase.md
plugins:
    - mknotebooks:
        binder: true
        binder_service_name: "gh"
        binder_branch: "SubhadityaMukherjee/openml_docs/attempting_to_unify_documentation"
        binder_ui: "lab"
    - redirects:
        redirect_maps:
            'APIs.md': 'https://www.openml.org/apis'
            'REST-API.md': 'https://www.openml.org/apis'
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js

